name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutterfire_ui: ^0.4.0
  firebase_core: 2.13.0
  firebase_database: any
  firebase_core_platform_interface: any
  firebase_auth: ^4.6.1



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.4
  shared_preferences: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/ellipse-4.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/
    - assets/page-1/images/vector-vLp.png
    - assets/page-1/images/vector-Tax.png
    - assets/page-1/images/vector-tJU.png
    - assets/page-1/images/vector-sJx.png
    - assets/page-1/images/ellipse-1.png
    - assets/page-1/images/vector-jbn.png
    - assets/page-1/images/vector-2xx.png
    - assets/page-1/images/vector-9SY.png
    - assets/page-1/images/unsplash-zz5lqe-vsmy.png
    - assets/page-1/images/vector-JME.png
    - assets/page-1/images/vector-h7W.png
    - assets/page-1/images/vector-MHi.png
    - assets/page-1/images/more-vertical.png
    - assets/page-1/images/vector-Qqe.png
    - assets/page-1/images/vector-55r.png
    - assets/page-1/images/vector-7on.png
    - assets/page-1/images/vector-h3E.png
    - assets/page-1/images/more-vertical-Gwa.png
    - assets/page-1/images/vector-7P6.png
    - assets/page-1/images/vector-aUx.png
    - assets/page-1/images/vector-zuv.png
    - assets/page-1/images/palette.png
    - assets/page-1/images/vector-WCg.png
    - assets/page-1/images/vector-kWt.png
    - assets/page-1/images/vector-97e.png
    - assets/page-1/images/vector-mhr.png
    - assets/page-1/images/unsplash-zz5lqe-vsmy-bg.png
    - assets/page-1/images/light-mode.png
    - assets/page-1/images/arrows-arrow-left.png
    - assets/page-1/images/unsplash-zz5lqe-vsmy-bg-V3n.png
    - assets/page-1/images/more-vertical-f44.png
    - assets/page-1/images/vector-go2.png
    - assets/page-1/images/google-logo-825006-1.png
    - assets/page-1/images/clear.png
    - assets/page-1/images/icon.png
    - assets/page-1/images/unsplash-zz5lqe-vsmy-bg-3LU.png
    - assets/page-1/images/istockphoto-1139451793-612x612-1.png
    - assets/page-1/images/unsplash-zz5lqe-vsmy-bg-Ybr.png
    - assets/page-1/images/ellipse-3.png
    - assets/page-1/images/vector-8xg.png
    - assets/page-1/images/vector-ifz.png
    - assets/page-1/images/vector-3iG.png
    - assets/page-1/images/vector-R4c.png
    - assets/page-1/images/icon-BpU.png
    - assets/page-1/images/icon-8SC.png
    - assets/page-1/images/vector-vJ4.png
    - assets/page-1/images/auto-group-nub2.png
    - assets/page-1/images/ellipse-3-Coi.png
    - assets/page-1/images/vector-eit.png
    - assets/page-1/images/ellipse-1-FVS.png
    - assets/page-1/images/notes230107152312d57-2.png
    - assets/page-1/images/aiforcustomerservicecover-1024w-2-bg.png
    - assets/page-1/images/vector-JRe.png
    - assets/page-1/images/vector-7hr.png
    - assets/page-1/images/vector-UB2.png
    - assets/page-1/images/vector-R6G.png
    - assets/page-1/images/ellipse-1-Ltg.png
    - assets/page-1/images/vector-1on.png
    - assets/page-1/images/unsplash-zz5lqe-vsmy-bg-Qun.png
    - assets/page-1/images/vector-nWt.png
    - assets/page-1/images/vector-8Mn.png
    - assets/page-1/images/vector-gu6.png
    - assets/page-1/images/undrawjoyridere968t-1-1.png
    - assets/page-1/images/google-logo-825006-1-mYt.png
    - assets/page-1/images/arrows-arrow-left-Vxc.png
    - assets/page-1/images/ellipse-1-Noz.png
    - assets/page-1/images/vector-Uxp.png
    - assets/page-1/images/security-shield-lock.png
    - assets/page-1/images/vector-MGL.png
    - assets/page-1/images/vector-Jtg.png
    - assets/page-1/images/unsplash-zz5lqe-vsmy-bg-3Wp.png
    - assets/page-1/images/auto-group-lpik.png
    - assets/page-1/images/unsplash-zz5lqe-vsmy-bg-7fE.png
    - assets/page-1/images/ellipse-1-x24.png
    - assets/page-1/images/vector-twJ.png
    - assets/page-1/images/vector-4Kz.png
    - assets/page-1/images/vector-q5r.png
    - assets/page-1/images/happy.png
    - assets/page-1/images/vector-MYc.png
    - assets/page-1/images/vector-WgQ.png
    - assets/page-1/images/unsplash-zz5lqe-vsmy-bg-RbW.png
    - assets/page-1/images/happy-42c.png
    - assets/page-1/images/calm-icon.png
    - assets/page-1/images/relax.png
    - assets/page-1/images/vector-LVv.png
    - assets/page-1/images/focus.png
    - assets/page-1/images/vector-noA.png
    - assets/page-1/images/ellipse-1-Lpg.png
    - assets/page-1/images/vector-jNG.png
    - assets/page-1/images/basemap-image.png
    - assets/page-1/images/check.png
    - assets/page-1/images/vector-B5A.png
    - assets/page-1/images/notes230107152312d57-1.png
    - assets/page-1/images/unsplash-zz5lqe-vsmy-DFN.png
    - assets/page-1/images/aiforcustomerservicecover-1024w-1-bg.png
    - assets/page-1/images/vector-XyS.png
    - assets/page-1/images/icon-Hhi.png
    - assets/page-1/images/unsplash-zz5lqe-vsmy-bg-tKS.png
    - assets/page-1/images/unsplash-zz5lqe-vsmy-bg-qhr.png
    - assets/page-1/images/relax-zak.png
    - assets/page-1/images/notes230107152312d57-1-uje.png
    - assets/page-1/images/notes230107152312d57-1-CeC.png
    - assets/page-1/images/arrows-arrow-left-fNg.png
    - assets/page-1/images/notes230107152312d57-2-rmv.png
    - assets/page-1/images/auto-group-scgy.png
    - assets/page-1/images/notes230107152312d57-1-bg.png
    - assets/page-1/images/ellipse-1-wvp.png
    - assets/page-1/images/vector-uGc.png
    - assets/page-1/images/ellipse-5.png
    - assets/page-1/images/avatar.png
    - assets/page-1/images/palette-fXv.png
    - assets/page-1/images/more-vertical-rPS.png
    - assets/page-1/images/security-shield-lock-MWY.png
    - assets/page-1/images/vector-ZKe.png
    - assets/page-1/images/vector-evk.png
    - assets/page-1/images/aiforcustomerservicecover-1024w-2-bg-ik8.png
    - assets/page-1/images/vector-gS4.png
    - assets/page-1/images/vector-bov.png
    - assets/page-1/images/vector-o4c.png
    - assets/page-1/images/vector-xoA.png
    - assets/page-1/images/vector-7vx.png
    - assets/page-1/images/unsplash-zz5lqe-vsmy-bg-5Mz.png
    - assets/page-1/images/icon-n1W.png
    - assets/page-1/images/aiforcustomerservicecover-1024w-2.png
    - assets/page-1/images/vector-K1S.png
    - assets/page-1/images/icon-GhN.png
    - assets/page-1/images/unsplash-zz5lqe-vsmy-bg-RqA.png
    - assets/page-1/images/ellipse-1-oBW.png
    - assets/page-1/images/notes230107152312d57-2-MTv.png
    - assets/page-1/images/ellipse-1-7xt.png
    - assets/page-1/images/vector-G5N.png
    - assets/page-1/images/ellipse-1-Yoa.png
    - assets/page-1/images/vector-7bn.png
    - assets/page-1/images/more-vertical-FaQ.png
    - assets/page-1/images/auto-group-btm6.png
    - assets/page-1/images/focus-zRW.png
    - assets/page-1/images/ellipse-1-93W.png
    - assets/page-1/images/auto-group-bnhe.png
    - assets/page-1/images/auto-group-yv32.png
    - assets/page-1/images/aiforcustomerservicecover-1024w-1-bg-QpQ.png
    - assets/page-1/images/aiforcustomerservicecover-1024w-2-bg-9GC.png
    - assets/page-1/images/vector-YVE.png
    - assets/page-1/images/notes230107152312d57-2-28g.png
    - assets/page-1/images/check-Mwe.png
    - assets/page-1/images/auto-group-sdyk.png
    - assets/page-1/images/ellipse-4-UmN.png
    - assets/page-1/images/notes230107152312d57-2-q68.png
    - assets/page-1/images/aiforcustomerservicecover-1024w-2-6NC.png
    - assets/page-1/images/vector-SPi.png
    - assets/page-1/images/more-vertical-hix.png
    - assets/page-1/images/vector-MVS.png
    - assets/page-1/images/vector-Cqn.png
    - assets/page-1/images/vector-wRa.png
    - assets/page-1/images/notes230107152312d57-2-QtG.png
    - assets/page-1/images/vector-nnc.png
    - assets/page-1/images/vector-s6Y.png
    - assets/page-1/images/vector-QrU.png
    - assets/page-1/images/basemap-image-sR2.png
    - assets/page-1/images/more-vertical-t3r.png
    - assets/page-1/images/vector-SWC.png
    - assets/page-1/images/vector-jB6.png
    - assets/page-1/images/vector-2yN.png
    - assets/page-1/images/vector-zQQ.png
    - assets/page-1/images/auto-group-ff2q.png
    - assets/page-1/images/vector-n7A.png
    - assets/page-1/images/vector-6Yx.png
    - assets/page-1/images/icon-VqA.png
    - assets/page-1/images/vector-uS8.png
    - assets/page-1/images/vector-vE4.png
    - assets/page-1/images/vector-mW8.png
    - assets/page-1/images/vector-ZXn.png
    - assets/page-1/images/vector-eKS.png
    - assets/page-1/images/vector-2DW.png
    - assets/page-1/images/auto-group-xyha.png
    - assets/page-1/images/vector-JME-sv8.png
    - assets/page-1/images/vector-KCt.png
    - assets/page-1/images/auto-group-9ufr.png
    - assets/page-1/images/arrows-arrow-left-urY.png
    - assets/page-1/images/vector-iqE.png
    - assets/page-1/images/arrows-arrow-left-UhE.png
    - assets/page-1/images/vector-RcU.png
    - assets/page-1/images/vector-qwe.png
    - assets/page-1/images/icon-WBA.png
    - assets/page-1/images/clear-GZe.png
    - assets/page-1/images/ellipse-1-EoJ.png
    - assets/page-1/images/vector-w2g.png
    - assets/page-1/images/vector-vYp.png
    - assets/page-1/images/icon-2ZW.png
    - assets/page-1/images/vector-V7W.png
    - assets/page-1/images/vector-xP2.png
    - assets/page-1/images/notes230107152312d57-2-mHr.png
    - assets/page-1/images/icon-Fng.png
    - assets/page-1/images/ellipse-1-eGg.png
    - assets/page-1/images/more-vertical-ahv.png
    - assets/page-1/images/vector-MXn.png
    - assets/page-1/images/ellipse-1-rAL.png
    - assets/page-1/images/unsplash-zz5lqe-vsmy-bg-8WL.png
    - assets/page-1/images/notes230107152312d57-3.png
    - assets/page-1/images/vector-z2k.png
    - assets/page-1/images/arrows-arrow-left-qsn.png
    - assets/page-1/images/calm-icon-w28.png
    - assets/page-1/images/unsplash-zz5lqe-vsmy-bg-Axg.png
    - assets/page-1/images/light-mode-gg8.png
    - assets/page-1/images/auto-group-m2xp.png
    - assets/page-1/images/unsplash-zz5lqe-vsmy-bg-rjr.png
    - assets/page-1/images/ellipse-1-rk8.png
    - assets/page-1/images/notes230107152312d57-3-AjS.png
    - assets/page-1/images/vector-63a.png
    - assets/page-1/images/vector-TQL.png
    - assets/page-1/images/notes230107152312d57-2-pV6.png
    - assets/page-2/images/icon-overview.png
    - assets/page-2/images/icon-battery.png
    - assets/page-1/images/unsplash-zz5lqe-vsmy-bg-MYt.png
    - assets/page-2/images/icon-back.png
    - assets/page-1/images/aiforcustomerservicecover-1024w-2-fya.png
    - assets/page-2/images/icon-back-Jh6.png
    - assets/page-2/images/icon-wifi.png
    - assets/page-2/images/vector-oBN.png
    - assets/page-2/images/vector-bZA.png
    - assets/page-1/images/aiforcustomerservicecover-1024w-1-bg-AG8.png
    - assets/page-2/images/vector-B4k.png
    - assets/page-2/images/icon-signal.png
    - assets/page-2/images/leading-icon.png
    - assets/page-1/images/aiforcustomerservicecover-1024w-1-bg-Zgc.png
    - assets/page-2/images/icon-wifi-cUG.png
    - assets/page-2/images/vector-7bn-tsS.png
    - assets/page-2/images/vector-6AC.png
    - assets/page-1/images/notes230107152312d57-2-AKa.png
    - assets/page-2/images/vector-wmS.png
    - assets/page-2/images/icon-signal-SC8.png
    - assets/page-2/images/icon-back-WoS.png
    - assets/page-2/images/icon-back-GrU.png
    - assets/page-2/images/icon-battery-Qac.png
    - assets/page-2/images/icon-back-rvc.png
    - assets/page-2/images/icon-overview-uzp.png
    - assets/page-2/images/vector-K4t.png
    - assets/page-1/images/notes230107152312d57-2-936.png
    - assets/page-1/images/vector-Pzp.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
